name: Android CI

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build android app
      run: ./gradlew assembleDebug
    - name: Build web app
      run: ./gradlew :web:assemble
    - name: Build iOS shared code
      run: ./gradlew :common:compileKotlinIOS
    - name: Build macOS shared code
      run: ./gradlew :common:compileKotlinMacOS

